enableGlobalCache: false
globalFolder: ".yarn/global"

packageExtensions:
  "leaflet-ant-path@*":
    peerDependencies:
      leaflet: "*"
    peerDependenciesMeta:
      leaflet:
        optional: true

nodeLinker: pnp