import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import storeLogin from "../hooks/storeLogin.ts";
import { useState } from "react";
function Login() {
    var _a = useState(''), email = _a[0], setEmail = _a[1];
    var _b = useState(''), password = _b[0], setPassword = _b[1];
    return (_jsx("div", { className: "flex justify-center items-center h-screen", children: _jsxs("div", { className: "bg-gray-100 p-5 rounded-lg shadow-md text-center", children: [_jsxs("div", { className: 'flex items-center justify-center p-2', children: [_jsx("img", { className: "logo w-10", src: "/mgb.png", alt: "Mass General Brigham" }), _jsx("div", { className: 'text-xl font-bold', children: _jsx("h2", { children: "Mass General Brigham" }) })] }), _jsxs("form", { className: "space-y-4", children: [_jsx("div", { children: _jsxs("label", { className: "block mb-1 text-left", children: ["Email:", _jsx("input", { type: "email", name: "email", value: email, onChange: function (e) { return setEmail(e.target.value); }, className: "w-full p-2 border border-gray-300 bg-white rounded" })] }) }), _jsx("div", { children: _jsxs("label", { className: "block mb-1 text-left", children: ["Password:", _jsx("input", { type: "password", name: "password", value: password, onChange: function (e) { return setPassword(e.target.value); }, className: "w-full p-2 border border-gray-300 bg-white rounded" })] }) }), _jsxs("div", { id: "rememberMe", className: "flex items-center space-x-0.5", children: [_jsx("label", { className: 'text-xs', children: "Remember Me:" }), _jsx("input", { id: "checkbox", type: "checkbox", name: "remember" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("button", { type: "submit", className: "px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700", children: "Guest Login" }), _jsx("button", { type: "submit", onClick: function () { return storeLogin(email, password); }, className: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-700", children: "Login" })] })] })] }) }));
}
export default Login;
