import client from "../apps/backend/src/bin/prisma-client.ts";


async function main() {
    // Chestnut hill floor 1
    await client.node.createMany({
        data: [
            {
                nodeID: 'canopyEntrance',
                nodeType: 'Entrance',
                building: 'Chestnut Hill',
                floor: 1,
                xcoord: 160.01,
                ycoord: 342.94,
                longName: 'Canopy Entrance',
                shortName: 'Canopy Entrance',
            },
            {
                nodeID: 'leftEntrance',
                nodeType: 'Entrance',
                building: 'Chestnut Hill',
                floor: 1,
                xcoord: 496.92,
                ycoord: 127.98,
                longName: 'Left Entrance',
                shortName: 'Left Entrance',
            },
            {
                nodeID: 'frontLotChestnut',
                nodeType: 'Parking',
                building: 'Chestnut Hill',
                floor: 1,
                xcoord: 130.02,
                ycoord: 592.9,
                longName: 'Front Parking Lot',
                shortName: 'Front Parking Lot',
            },
            {
                nodeID: 'leftWaiting',
                nodeType: 'Other',
                building: 'Chestnut Hill',
                floor: 1,
                xcoord: 437.93,
                ycoord: 152.98,
                longName: 'Left Waiting Area',
                shortName: 'Left Waiting Area',
            },
            {
                nodeID: 'leftLotChestnut',
                nodeType: 'Parking',
                building: 'Chestnut Hill',
                floor: 1,
                xcoord: 587.89,
                ycoord: 20.0,
                longName: 'Left Parking Lot',
                shortName: 'Left Parking Lot',
            },
            {
                nodeID: 'specialtyCheckIn',
                nodeType: 'Reception',
                building: 'Chestnut Hill',
                floor: 1,
                xcoord: 262.98,
                ycoord: 449.93,
                longName: 'Speciality Check In',
                shortName: 'Specialty Check In',
            },
            {
                nodeID: 'canopyEntranceHallway',
                nodeType: 'Hallway',
                building: 'Chestnut Hill',
                floor: 1,
                xcoord: 179.01,
                ycoord: 343.94,
                longName: 'Canopy Entrance Hallway',
                shortName: 'Canopy Entrance Hallway',
            },
        ],
        skipDuplicates: true,
    });

// patriot 20 floor 1
    await client.node.createMany({
        data: [
            {
                nodeID: 'valetParking20',
                nodeType: 'Parking',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 594.87,
                ycoord: 43.05,
                longName: 'Valet Parking 20 Patriot',
                shortName: 'Valet Parking',
            },
            {
                nodeID: 'patientParking20',
                nodeType: 'Parking',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 166.45,
                ycoord: 36.5,
                longName: 'Patient Parking 20 Patriot',
                shortName: 'Patient Parking',
            },
            {
                nodeID: 'extendedParking20',
                nodeType: 'Parking',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 125.94,
                ycoord: 265.92,
                longName: 'Extended Patient Parking 20 Patriot',
                shortName: 'Extended Patient Parking',
            },
            {
                nodeID: 'swEntrance',
                nodeType: 'Entrance',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 186.48,
                ycoord: 134.0,
                longName: 'SW Entrance',
                shortName: 'SW Entrance',
            },
            {
                nodeID: 'seEntrance',
                nodeType: 'Entrance',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 253.24,
                ycoord: 841.5,
                longName: 'SE Entrance',
                shortName: 'SE Entrance',
            },
            {
                nodeID: '130.01',
                nodeType: 'Reception',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 333.24,
                ycoord: 342.0,
                longName: 'Reception 130.01',
                shortName: 'Reception',
            },
            {
                nodeID: '110.01',
                nodeType: 'Reception',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 412.74,
                ycoord: 221.0,
                longName: 'Check-In 110.01',
                shortName: 'Check-In',
            },
            {
                nodeID: '120.01',
                nodeType: 'Reception',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 256.24,
                ycoord: 466.0,
                longName: 'Check-In 120.01',
                shortName: 'Check-In',
            },
            {
                nodeID: '100.00F',
                nodeType: 'Reception',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 190.74,
                ycoord: 589.5,
                longName: 'Check-In 100.00F',
                shortName: 'Check-In',
            },
            {
                nodeID: '100.13',
                nodeType: 'Stairs',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 767.24,
                ycoord: 243.0,
                longName: 'Stairs 100.13',
                shortName: 'Stairs',
            },
            {
                nodeID: '100.14',
                nodeType: 'Stairs',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 218.74,
                ycoord: 818.0,
                longName: 'Stairs 100.14',
                shortName: 'Stairs',
            },
            {
                nodeID: '100.10',
                nodeType: 'Elevator',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 191.74,
                ycoord: 757.5,
                longName: 'Elevator 100.10',
                shortName: 'Elevator',
            },
            {
                nodeID: '100.00',
                nodeType: 'Hallway',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 192.74,
                ycoord: 234.5,
                longName: 'Lobby 100.00 intersection',
                shortName: 'Lobby',
            },
            {
                nodeID: '100.04',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 458.74,
                ycoord: 234.5,
                longName: 'Pharmacy Consult',
                shortName: 'Pharmacy Consult',
            },
            {
                nodeID: '110.20A',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 519.24,
                ycoord: 231.5,
                longName: 'Patient Toilet 110.20A',
                shortName: 'Patient Toilet',
            },
            {
                nodeID: '110.03',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 520.24,
                ycoord: 258.0,
                longName: 'Public Toilet 110.03',
                shortName: 'Public Toilet',
            },
            {
                nodeID: '110.20',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 570.24,
                ycoord: 258.5,
                longName: 'Ultrasound 6 110.20',
                shortName: 'Ultrasound 6',
            },
            {
                nodeID: '110.09',
                nodeType: 'Hallway',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 682.24,
                ycoord: 259.5,
                longName: 'Corridor 110.09',
                shortName: 'Corridor',
            },
            {
                nodeID: '110.12A',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 721.74,
                ycoord: 254.5,
                longName: 'Water Service 110.12A',
                shortName: 'Water Service',
            },
            {
                nodeID: '110.33',
                nodeType: 'Hallway',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 575.24,
                ycoord: 518.5,
                longName: 'Corridor 110.33',
                shortName: 'Corridor',
            },
            {
                nodeID: '110.60',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 549.74,
                ycoord: 536.0,
                longName: 'Sub Wait 110.60',
                shortName: 'Sub Wait',
            },
            {
                nodeID: '120.26',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 418.24,
                ycoord: 532.5,
                longName: 'Practice Manager 120.26',
                shortName: 'Practice Manager',
            },
            {
                nodeID: '100.09',
                nodeType: 'Hallway',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 191.24,
                ycoord: 530.5,
                longName: 'Corridor 100.09',
                shortName: 'Corridor',
            },
            {
                nodeID: '120.00B',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 196.74,
                ycoord: 451.5,
                longName: 'Wheelchair Storage 120.00B',
                shortName: 'Wheelchair Storage',
            },
            {
                nodeID: '150.30',
                nodeType: 'Hallway',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 338.74,
                ycoord: 702.5,
                longName: 'Corridor 150.30',
                shortName: 'Corridor',
            },
            {
                nodeID: '150.36',
                nodeType: 'Hallway',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 311.24,
                ycoord: 672.5,
                longName: 'Corridor 150.36',
                shortName: 'Corridor',
            },
            {
                nodeID: '130.00',
                nodeType: 'Other',
                building: 'Patriot Place 20',
                floor: 1,
                xcoord: 324.74,
                ycoord: 247.0,
                longName: 'Waiting Room 130.00',
                shortName: 'Waiting Room',
            },
        ],
        skipDuplicates: true,
    });

// patriot 20 floor 3
    await client.node.createMany({
        data: [
            {
                nodeID: 'bridgePatriot20',
                nodeType: 'Entrance',
                building: 'Patriot Place 20',
                floor: 3,
                xcoord: 237.41,
                ycoord: 111.0,
                longName: 'Bridge from 20 Patriot',
                shortName: 'Bridge',
            },
            {
                nodeID: '300.13',
                nodeType: 'Stairs',
                building: 'Patriot Place 20',
                floor: 3,
                xcoord: 767.24,
                ycoord: 243.0,
                longName: '3rd Floor Stairs',
                shortName: '3rd Floor Stairs',
            },
            {
                nodeID: '300.14',
                nodeType: 'Stairs',
                building: 'Patriot Place 20',
                floor: 3,
                xcoord: 218.74,
                ycoord: 818.0,
                longName: '3rd Floor Stairs',
                shortName: '3rd Floor Stairs',
            },
            {
                nodeID: '300.10',
                nodeType: 'Elevator',
                building: 'Patriot Place 20',
                floor: 3,
                xcoord: 191.74,
                ycoord: 757.5,
                longName: '3rd Floor Elevator',
                shortName: '3rd Floor Elevator',
            },
        ],
        skipDuplicates: true,
    });

// patriot 22 floor 1
    await client.node.createMany({
        data: [
            {
                nodeID: 'valetParking22',
                nodeType: 'Parking',
                building: 'Patriot Place 22',
                floor: 1,
                xcoord: 576.44,
                ycoord: 35.1,
                longName: 'Valet Parking 22 Patriot',
                shortName: 'Valet Parking',
            },
            {
                nodeID: 'patientParking22',
                nodeType: 'Parking',
                building: 'Patriot Place 22',
                floor: 1,
                xcoord: 217.98,
                ycoord: 221.99,
                longName: 'Patient Parking 22 Patriot',
                shortName: 'Patient Parking',
            },
            {
                nodeID: 'extendedParking22',
                nodeType: 'Parking',
                building: 'Patriot Place 22',
                floor: 1,
                xcoord: 128.7,
                ycoord: 226.15,
                longName: 'Extended Patient Parking 22 Patriot',
                shortName: 'Extended Patient Parking',
            },
            {
                nodeID: '1ST01',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 1,
                xcoord: 419.75,
                ycoord: 455.0,
                longName: '', // No long name provided
                shortName: '1st Floor Stairs', // Added descriptive name
            },
            {
                nodeID: '1ST02',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 1,
                xcoord: 355.25,
                ycoord: 280.5,
                longName: '', // No long name provided
                shortName: '1st Floor Stairs', // Added descriptive name
            },
            {
                nodeID: '1EA',
                nodeType: 'Elevator',
                building: 'Patriot Place 22',
                floor: 1,
                xcoord: 351.25,
                ycoord: 535.5,
                longName: 'Elevator 1A',
                shortName: 'Elevator 1A',
            },
            {
                nodeID: '22entrance1',
                nodeType: 'Entrance',
                building: 'Patriot Place 22',
                floor: 1,
                xcoord: 333.39,
                ycoord: 719.0,
                longName: 'Entrance',
                shortName: 'Entrance',
            },
        ],
        skipDuplicates: true,
    });

// patriot 22 floor 3
    await client.node.createMany({
        data: [
            {
                nodeID: 'ST02',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 442.88,
                ycoord: 327.0,
                longName: 'Stair ST02',
                shortName: 'Stair',
            },
            {
                nodeID: '3000C',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 444.25,
                ycoord: 344.0,
                longName: 'Copy 3000C',
                shortName: 'Copy Room',
            },
            {
                nodeID: '3E',
                nodeType: 'Hallway',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 466.88,
                ycoord: 345.0,
                longName: 'Corridor 3E',
                shortName: 'Corridor',
            },
            {
                nodeID: '3001',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 466.63,
                ycoord: 432.0,
                longName: 'Touchdown 3001',
                shortName: 'Touchdown',
            },
            {
                nodeID: '3000A',
                nodeType: 'Reception',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 418.63,
                ycoord: 419.25,
                longName: 'Check-In 3000A',
                shortName: 'Check-In',
            },
            {
                nodeID: 'ST01',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 436.13,
                ycoord: 470.25,
                longName: 'Tenant Stair ST01',
                shortName: 'Tenant Stair',
            },
            {
                nodeID: '3A',
                nodeType: 'Elevator',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 438.88,
                ycoord: 538.75,
                longName: 'Elevator 3A',
                shortName: 'Elevator',
            },
            {
                nodeID: '3B',
                nodeType: 'Hallway',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 438.13,
                ycoord: 592.5,
                longName: 'Corridor 3B',
                shortName: 'Corridor',
            },
            {
                nodeID: '3000B',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 436.13,
                ycoord: 643.75,
                longName: 'Waiting 3000B',
                shortName: 'Waiting Area',
            },
            {
                nodeID: '3104',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 595.13,
                ycoord: 639.0,
                longName: 'EQ Alcohol 3104',
                shortName: 'EQ Alcohol',
            },
            {
                nodeID: '3S',
                nodeType: 'Hallway',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 595.13,
                ycoord: 733.25,
                longName: 'Corridor 3S',
                shortName: 'Corridor',
            },
            {
                nodeID: '3112',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 645.88,
                ycoord: 732.5,
                longName: 'Exam 3112',
                shortName: 'Exam Room',
            },
            {
                nodeID: 'ST03',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 660.63,
                ycoord: 805.25,
                longName: 'Stair ST03',
                shortName: 'Stair',
            },
            {
                nodeID: '307',
                nodeType: 'Hallway',
                building: 'Patriot Place 22',
                floor: 3,
                xcoord: 275.38,
                ycoord: 693.5,
                longName: 'Bridge 307',
                shortName: 'Bridge',
            },
        ],
        skipDuplicates: true,
    });

// patriot 22 floor 4
    await client.node.createMany({
        data: [
            {
                nodeID: 'checkIn4000B',
                nodeType: 'Reception',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 319.25,
                ycoord: 654.5,
                longName: 'rightCheckIn',
                shortName: 'Right Check-In',
            },
            {
                nodeID: 'waiting4000',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 299.25,
                ycoord: 579.5,
                longName: 'rightEntranceWaiting',
                shortName: 'Right Entrance Waiting',
            },
            {
                nodeID: 'rightWaitingHallway',
                nodeType: 'Hallway',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 250.25,
                ycoord: 633.5,
                longName: 'rightWaitingHallway',
                shortName: 'Right Waiting Hallway',
            },
            {
                nodeID: 'rightEntranceHallway',
                nodeType: 'Hallway',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 353.25,
                ycoord: 655.5,
                longName: 'rightEntranceHallway',
                shortName: 'Right Entrance Hallway',
            },
            {
                nodeID: 'elevatorLobby4A',
                nodeType: 'Elevator',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 351.25,
                ycoord: 535.5,
                longName: 'elevatorLobby',
                shortName: 'Elevator Lobby',
            },
            {
                nodeID: 'lobbyStairsHallway',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 350.75,
                ycoord: 455.5,
                longName: 'lobbyStairsHallway',
                shortName: 'Lobby Stairs Hallway',
            },
            {
                nodeID: 'stairST01',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 419.75,
                ycoord: 455.0,
                longName: 'lobbyStairs',
                shortName: 'Lobby Stairs',
            },
            {
                nodeID: 'stairST02',
                nodeType: 'Stairs',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 355.25,
                ycoord: 280.5,
                longName: 'leftStairs',
                shortName: 'Left Stairs',
            },
            {
                nodeID: 'corridor4R',
                nodeType: 'Hallway',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 468.75,
                ycoord: 653.5,
                longName: 'checkOutHallway',
                shortName: 'Check-Out Hallway',
            },
            {
                nodeID: 'checkOutWait4083',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 470.25,
                ycoord: 615.0,
                longName: 'checkOutWait',
                shortName: 'Check-Out Waiting',
            },
            {
                nodeID: 'checkOut4090',
                nodeType: 'Other',
                building: 'Patriot Place 22',
                floor: 4,
                xcoord: 497.25,
                ycoord: 708.0,
                longName: 'checkOut',
                shortName: 'Check-Out',
            },
        ],
        skipDuplicates: true,
    });

// faulkner floor 1
    await client.node.createMany({
        data: [
            {
                nodeID: 'valetParkingFaulkner',
                nodeType: 'Parking',
                building: 'Faulkner',
                floor: 1,
                xcoord: 0,
                ycoord: 0,
                longName: 'Valet Parking Lot',
                shortName: 'Valet Parking Lot',
            },
            {
                nodeID: 'leftLotFaulkner',
                nodeType: 'Parking',
                building: 'Faulkner',
                floor: 1,
                xcoord: 0,
                ycoord: 0,
                longName: 'Left Parking Lot',
                shortName: 'Left Parking Lot',
            },
            {
                nodeID: 'rightLotFaulkner',
                nodeType: 'Parking',
                building: 'Faulkner',
                floor: 1,
                xcoord: 0,
                ycoord: 0,
                longName: 'Right Parking Lot',
                shortName: 'Right Parking Lot',
            },
        ],
        skipDuplicates: true,
    });

    console.log('Floorplan seeded successfully!');
    }

    main()
        .catch((e) => {
            console.error(e);
            return Promise.reject(e);
        })
        .finally(async () => {
            await client.$disconnect();
        });