export interface RawDirectoryItem {
    name: string;
    floorNumber: number;
    building: string;
}

export const rawDirectoryItems: RawDirectoryItem[] = [
    {name: "Blood Draw/Phlebotomy", floorNumber: 1, building: "PATRIOT_PLACE_20"},
    {name: "Pharmacy", floorNumber: 1, building: "PATRIOT_PLACE_20"},
    {name: "Radiology", floorNumber: 1, building: "PATRIOT_PLACE_20"},
    {name: "Cardiovascular Services", floorNumber: 1, building: "PATRIOT_PLACE_20"},
    {name: "Urology", floorNumber: 1, building: "PATRIOT_PLACE_20"},
    {name: "Urgent Care Center", floorNumber: 1, building: "PATRIOT_PLACE_20"},

    {name: "Orthopaedics", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Hand and Upper Extremity", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Arthroplasty", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Pediatric Trauma", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Physiatry", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Podiatry", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Rehabilitation Services", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Cardiac Rehab", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Occupational Therapy", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Hand Therapy", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Upper Extremity", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Physical Therapy", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Speech - Language", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Clinical Lab", floorNumber: 2, building: "PATRIOT_PLACE_20"},
    {name: "Surgi-Care", floorNumber: 2, building: "PATRIOT_PLACE_20"},

    {name: "Surgical Specialties", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "Audiology", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "ENT", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "General and Gastrointestinal Surgery", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "Plastic Surgery", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "Thoriacic Surgery", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "Vascular Surgery", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "Weight Management and Wellness", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "Sports Medicine Center", floorNumber: 3, building: "PATRIOT_PLACE_20"},
    {name: "X-Rat Suite", floorNumber: 3, building: "PATRIOT_PLACE_20"},

    {name: "Electromyography", floorNumber: 4, building: "PATRIOT_PLACE_20"},
    {name: "Nutrition", floorNumber: 4, building: "PATRIOT_PLACE_20"},
    {name: "Pain Medicine", floorNumber: 4, building: "PATRIOT_PLACE_20"},
    {name: "Physiatry", floorNumber: 4, building: "PATRIOT_PLACE_20"},
    {name: "Pulmonary Function Testing", floorNumber: 4, building: "PATRIOT_PLACE_20"},
    {name: "Day Surgery Center", floorNumber: 4, building: "PATRIOT_PLACE_20"},

    {name: "MassGeneral Hospital for Children", floorNumber: 1, building: "PATRIOT_PLACE_22"},
    {name: "Spaulding Outpatient Care for Children", floorNumber: 1, building: "PATRIOT_PLACE_22"},

    {name: "Multi Specialty Clinic", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Allergy", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Cardiac Arrhythmia", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Dermatology", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Endocrinology", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Gastroenterology", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Kidney (Renal) Medicine", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Neurology", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Neurosurgery", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Opthalmology", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Optometry", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Pulmonology", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Rhematology", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Vein Care Services", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Women's Health", floorNumber: 3, building: "PATRIOT_PLACE_22"},
    {name: "Patient Financial Services", floorNumber: 3, building: "PATRIOT_PLACE_22"},

    {name: "Blood Draw/Phlebotomy", floorNumber: 4, building: "PATRIOT_PLACE_22"},
    {name: "Community Room", floorNumber: 4, building: "PATRIOT_PLACE_22"},
    {name: "Primary Care", floorNumber: 4, building: "PATRIOT_PLACE_22"},


    {name: "Laboratory", floorNumber: 1, building: "CHESTNUT_HILL"},
    {name: "Multi-Specialty Clinic", floorNumber: 1, building: "CHESTNUT_HILL"},
    {name: "Radiology (MRI/CT Scan)", floorNumber: 1, building: "CHESTNUT_HILL"},

    {name: "Backup Child Care Center", floorNumber: 2, building: "CHESTNUT_HILL"},
    {name: "Crohn's and Colitis Center", floorNumber: 2, building: "CHESTNUT_HILL"},
    {name: "Endoscopy Center", floorNumber: 2, building: "CHESTNUT_HILL"},
    {name: "Patient Financial Services", floorNumber: 2, building: "CHESTNUT_HILL"},
    {name: "Rehabilitation Services", floorNumber: 2, building: "CHESTNUT_HILL"},


    {name: "Allergy and Clinical Immunology", floorNumber: 3, building: "CHESTNUT_HILL"},
    {name: "Brigham Dermatology Associates (BDA)", floorNumber: 3, building: "CHESTNUT_HILL"},
    {name: 'Brigham Psychiatric Specialties', floorNumber: 3, building: "CHESTNUT_HILL"},
    {name: "Center for Pain Medicine", floorNumber: 3, building: "CHESTNUT_HILL"},
    {name: "Pharmacy", floorNumber: 3, building: "CHESTNUT_HILL"},


    {name: "Brigham Physicians Group (BPG)", floorNumber: 4, building: "CHESTNUT_HILL"},
    {name: 'Gretchen S. and Edward A. Fish Center for Women\'s Health', floorNumber: 4, building: "CHESTNUT_HILL"},
    {name: 'Osher Clinical Center for Integrative Health', floorNumber: 4, building: "CHESTNUT_HILL"},

    {name: "Allergy and Clinical Immunology", floorNumber: 5, building: "CHESTNUT_HILL"},
    {name: 'Brigham Obstetrics and Gynecology Group (BOGG)', floorNumber: 5, building: "CHESTNUT_HILL"},
    {name: 'Brigham Physicians Group (BPG)', floorNumber: 5, building: "CHESTNUT_HILL"},
    {name: "Radiology", floorNumber: 5, building: "CHESTNUT_HILL"},

    {name: "Admitting/Registration", floorNumber: 1, building: "FAULKNER"},
    {name: "Atrium Cafe", floorNumber: 1, building: "FAULKNER"},
    {name: "Audiology", floorNumber: 1, building: "FAULKNER"},
    {name: "Blood Drawing Lab", floorNumber: 1, building: "FAULKNER"},
    {name: "Cardiac Rehab", floorNumber: 1, building: "FAULKNER"},
    {name: "Emergency Department", floorNumber: 1, building: "FAULKNER"},
    {name: "Emergency Entrance", floorNumber: 1, building: "FAULKNER"},
    {name: "GI Endoscopy", floorNumber: 1, building: "FAULKNER"},
    {name: "Information", floorNumber: 1, building: "FAULKNER"},
    {name: "MRI/CT", floorNumber: 1, building: "FAULKNER"},
    {name: "Patient Finances", floorNumber: 1, building: "FAULKNER"},
    {name: "Pre-Admittance Screening", floorNumber: 1, building: "FAULKNER"},
    {name: "Pulmonary Lab", floorNumber: 1, building: "FAULKNER"},
    {name: "Radiology", floorNumber: 1, building: "FAULKNER"},
    {name: "Special Testing", floorNumber: 1, building: "FAULKNER"},
    {name: "Starbucks", floorNumber: 1, building: "FAULKNER"},
    {name: "Taiclet Family Center", floorNumber: 1, building: "FAULKNER"},
    {name: "Vascular Lab", floorNumber: 1, building: "FAULKNER"},

    {name: 'Biomedical Engineering', floorNumber: 2, building: "FAULKNER"},
    {name: 'Food Services', floorNumber: 2, building: "FAULKNER"},
    {name: 'Morgue', floorNumber: 2, building: "FAULKNER"},
    {name: 'Occupational Therapy', floorNumber: 2, building: "FAULKNER"},
    {name: 'Otolaryngology', floorNumber: 2, building: "FAULKNER"},
    {name: 'Pharmacy', floorNumber: 2, building: "FAULKNER"},
    {name: 'Physical Therapy', floorNumber: 2, building: "FAULKNER"},
    {name: 'Plastic Surgery', floorNumber: 2, building: "FAULKNER"},
    {name: 'Psychiatric Inpatient Care', floorNumber: 2, building: "FAULKNER"},
    {name: 'Psychiatric/Addiction Recovery', floorNumber: 2, building: "FAULKNER"},
    {name: 'Rehabilitation Services', floorNumber: 2, building: "FAULKNER"},

    {name: 'Cafeteria', floorNumber: 3, building: "FAULKNER"},
    {name: 'Chapel', floorNumber: 3, building: "FAULKNER"},
    {name: 'Family/Patient Resources', floorNumber: 3, building: "FAULKNER"},
    {name: 'Gift Shop', floorNumber: 3, building: "FAULKNER"},
    {name: 'Gynecology & Oncology', floorNumber: 3, building: "FAULKNER"},
    {name: 'Huvos Auditorium', floorNumber: 3, building: "FAULKNER"},
    {name: 'Information', floorNumber: 3, building: "FAULKNER"},
    {name: 'Obstetrics and Gynecology Associates', floorNumber: 3, building: "FAULKNER"},
    {name: 'Outdoor Dining Terrace', floorNumber: 3, building: "FAULKNER"},
    {name: 'Roslindale Pediatric Associates', floorNumber: 3, building: "FAULKNER"},
    {name: 'Shuttle Pickup', floorNumber: 3, building: "FAULKNER"},
    {name: 'Volunteer Services', floorNumber: 3, building: "FAULKNER"},

    {name: 'Cardiology', floorNumber: 4, building: "FAULKNER"},
    {name: 'Foot and Ankle Center', floorNumber: 4, building: "FAULKNER"},
    {name: 'Gastroenterology Associates', floorNumber: 4, building: "FAULKNER"},
    {name: 'HVMA Internal Medicine', floorNumber: 4, building: "FAULKNER"},
    {name: 'HVMA Neurology', floorNumber: 4, building: "FAULKNER"},
    {name: 'Medical Library', floorNumber: 4, building: "FAULKNER"},
    {name: 'Medical Records', floorNumber: 4, building: "FAULKNER"},
    {name: 'MOHS Clinic', floorNumber: 4, building: "FAULKNER"},
    {name: 'Neurology', floorNumber: 4, building: "FAULKNER"},
    {name: 'Primary care Physicians', floorNumber: 4, building: "FAULKNER"},
    {name: 'Pulmonary Services', floorNumber: 4, building: "FAULKNER"},
    {name: 'Rheumatology Center', floorNumber: 4, building: "FAULKNER"},
    {name: 'Sadowsky Conference Room', floorNumber: 4, building: "FAULKNER"},
    {name: 'Social Work', floorNumber: 4, building: "FAULKNER"},
    {name: 'Tynan Conference Room', floorNumber: 4, building: "FAULKNER"},
    {name: 'Urology', floorNumber: 4, building: "FAULKNER"},

    {name: 'Boston ENT Associates', floorNumber: 5, building: "FAULKNER"},
    {name: 'Endocrinology/Diabetes/Hemotology', floorNumber: 5, building: "FAULKNER"},
    {name: 'Headache', floorNumber: 5, building: "FAULKNER"},
    {name: 'ICU', floorNumber: 5, building: "FAULKNER"},
    {name: 'Internal Medicine', floorNumber: 5, building: "FAULKNER"},
    {name: 'Oncology Clinic', floorNumber: 5, building: "FAULKNER"},
    {name: 'Orthopaedic Associates', floorNumber: 5, building: "FAULKNER"},
    {name: 'Outpatient Infusion Center', floorNumber: 5, building: "FAULKNER"},
    {name: 'Primary Care Physicians', floorNumber: 5, building: "FAULKNER"},
    {name: 'Surgical Specialties', floorNumber: 5, building: "FAULKNER"},
    {name: 'X-Ray', floorNumber: 5, building: "FAULKNER"},
    {name: 'X-Ray Waiting Room', floorNumber: 5, building: "FAULKNER"},
];