export const API_ROUTES = {
    HEALTHCHECK: '/api/healthcheck',
    EMPLOYEE: '/api/employee',
    SERVICE: '/api/servicereq',
    ASSIGNED: '/api/assigned',
    LOGIN: '/api/login',
    SANITATION: '/api/sanitation',
    CSV: '/api/csv',
    ALGO: '/api/algo',
    PATIENTREQ: '/api/patientreq',
    PHARMACY: '/api/pharmacy',
    ENUM: '/api/enum',
    TRANSPORT: '/api/transportreq',
    DEVICE: '/api/devicereq',
    MAP: '/api/map',
    ASTAR: '/api/aStar',
    DFS: '/api/dfs',
    TRANSLATE: '/api/translate',
    INLINETRANSLATOR: '/api/inline',
    UPLOADTRANSLATE: '/api/upload-translate',
    ANNOUNCEMENTS: '/api/announcements',
    NOTIFICATIONS: '/api/notifications',
};
